version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/common"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/composer/helpers/v1"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/composer/helpers/v2"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/npm_and_yarn/helpers"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "npm"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "pip"
    directory: "/python/helpers"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
