name: Lint

on: [push] # what if it lints for something that isn't there :panik:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flynt black isort[requirements_deprecated_finder]
    - name: isort
      run: isort . --profile black
    - name: Black
      run: black ./ --line-length=120
    - name: Flynt
      run: flynt ./ -tc
    - name: Setup Git
      run: |
          git config user.name "Automated Linter"
    - name: Push To Git
      continue-on-error: true
      run: |
          git pull
          git add . || exit 0
          git commit --reuse-message=HEAD || exit 0
          git push || exit 0
